{% set version = "2.9.8" %}
{% if linux %}
    {% set libext = ".so" %}
{% elif osx %}
    {% set libext = ".dylib" %}
{% else %}
    {% set libext = ".a" %}
{% endif %}

{% set variant = "mkl" %}


package:
  name: coincbc
  version: {{ version }}

source:
  fn: Cbc-{{ version }}.tgz
  url: http://www.coin-or.org/download/source/Cbc/Cbc-{{ version }}.tgz
  sha256: ff6860400a1390170f9cb19fab6f21c1997138d285b5f225be04c4642c9a7bea

build:
  number: 1
  # features:
  #   - {{ variant }}

requirements:
  build:
    - m2-base # [win]
    - m2-make # [win]
    - m2w64-toolchain # [win]
    - gcc # [not win]
    - mkl
  run:
    #- m2w64-gcc-libs
    - libgcc # [not win]
    - mkl # [not win]

# test:
#   commands:
#     - test -f "${PREFIX}/lib/libCbc{{ libext }}" # [not win]
#     - test -f "${PREFIX}/lib/libCbcSolver{{ libext }}" # [not win]
#     - test -f "${PREFIX}/lib/libCgl{{ libext }}" # [not win]
#     - test -f "${PREFIX}/lib/libClp{{ libext }}" # [not win]
#     - test -f "${PREFIX}/lib/libClpSolver{{ libext }}" # [not win]
#     - test -f "${PREFIX}/lib/libCoinUtils{{ libext }}" # [not win]
#     - test -f "${PREFIX}/lib/libOsi{{ libext }}" # [not win]
#     - test -f "${PREFIX}/lib/libOsiCbc{{ libext }}" # [not win]
#     - test -f "${PREFIX}/lib/libOsiClp{{ libext }}" # [not win]
#     - test -f "${PREFIX}/lib/libOsiCommonTests{{ libext }}" # [not win]
    # - test -f "%PREFIX%/lib/libCbc{{ libext }}" # [win]
    # - test -f "%PREFIX%/lib/libCbcSolver{{ libext }}" # [win]
    # - test -f "%PREFIX%/lib/libCgl{{ libext }}" # [win]
    # - test -f "%PREFIX%/lib/libClp{{ libext }}" # [win]
    # - test -f "%PREFIX%/lib/libClpSolver{{ libext }}" # [win]
    # - test -f "%PREFIX%/lib/libCoinUtils{{ libext }}" # [win]
    # - test -f "%PREFIX%/lib/libOsi{{ libext }}" # [win]
    # - test -f "%PREFIX%/lib/libOsiCbc{{ libext }}" # [win]
    # - test -f "%PREFIX%/lib/libOsiClp{{ libext }}" # [win]
    # - test -f "%PREFIX%/lib/libOsiCommonTests{{ libext }}" # [win]

about:
  home: http://www.coin-or.org/
  license: Eclipse Public License v1.0
  summary: "Cbc (Coin-or branch and cut) is an open-source mixed integer programming solver written in C++."

extra:
  recipe-maintainers:
    - scopatz
    - gidden
    - whart222
    - jjhelmus
    - lsorber
    - mathieu1
